### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by randhana** [randhana/Drowning-Detection-#15]
UserWarning: Trying to unpickle estimator LabelBinarizer from version 0.22.2.post1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  UserWarning,
Loading model and label binarizer...
Model Loaded...
Loaded model state_dict...
Downloading yolov3.cfg from https://github.com/randhana/Drowning-Detection-/blob/master/yolov3.cfg
Traceback (most recent call last):############################################|
  File "DrownDetect.py", line 152, in <module>
    detectDrowning(args.source)
  File "DrownDetect.py", line 79, in detectDrowning
    bbox, label, conf = cv.detect_common_objects(frame)
  File "C:\Users\winuser\Desktop\Drowning-Detection--master\Drowning-Detection--master\cvlib\object_detection.py", line 99, in detect_common_objects
    download_file(url=url, file_name=config_file_name, dest_dir=dest_dir)
  File "C:\Users\winuser\Desktop\Drowning-Detection--master\Drowning-Detection--master\cvlib\utils.py", line 38, in download_file
    bar.update(count)
  File "C:\Users\winuser\Desktop\Drowning-Detection--master\Drowning-Detection--master\env\lib\site-packages\progressbar\progressbar.py", line 250, in update
    raise ValueError('Value out of range')
ValueError: Value out of range

**Comment by randhana** [comment]
**Issue Description**:
I encountered an issue in the cvlib/utils.py file and the cvlib/object_detection.py file where the progress bar value was going out of range, leading to a ValueError. This happened during the execution of the DrownDetect.py script. The issue was traced back to the progressbar library not handling the value update properly.

**Fix**:
In cvlib/utils.py, I ensured that the progress bar value doesn't exceed its maximum value, addressing the out-of-range issue.
In cvlib/object_detection.py, I updated the URLs to use the GitHub username and repository for improved accessibility.
